### ISSUE TITLE
Error while running sweetroll2.setup

### ISSUE THREAD

**Issue by abhas** [myfreeweb/sweetroll2#3]
While running the `mix` task `sweetroll2.setup`, it fails while trying to compile and install dependencies with the following error:

```
could not compile dependency :html5ever, "mix compile" failed. You can recompile this dependency with "mix deps.compile html5ever", update it with "mix deps.update html5ever" or clean it with "mix deps.clean html5ever"
** (ErlangError) Erlang error: :enoent
    (elixir 1.11.2) lib/system.ex:815: System.cmd("cargo", ["rustc", "--no-default-features", "--release"], [cd: "/usr/local/web/sweetroll2/deps/html5ever/native/html5ever_nif", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/usr/local/web/sweetroll2/_build/dev/rustler_crates/html5ever_nif"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:59: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
```

I'm trying to use elixir for the first time and don't really know how to debug this. I did try to run `mix deps.compile html5ever` but it fails with the same error as above.

**Comment by unrelentingtech** [comment]
You need `cargo` to build Rust dependencies. Get it from https://rustup.rs

BTW, this engine is not very actively maintained anymore, play around at your own risk.
